---
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"

---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE
)

# Library and environment set up ----

library(sf)
library(dplyr)
library(scales)
library(rmapshaper)
library(leaflet)
library(leaflet.extras)
library(htmlwidgets)
options(scipen=999)

# Colors and Fonts ----
## COLORS ##
papaya <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

# Load in and prep shapes ----
source("W:\\RDA Team\\R\\credentials_source.R")

con_alt <- connect_to_db("altadena_recovery_rebuild")

# eaton fire shape -
eaton_fire <- st_read(con_alt, query="SELECT * FROM data.eaton_fire_prmtr_3310", geom="geom")

# east and west altadena boundaries --
west <- st_read(con_alt, query="SELECT * FROM data.west_altadena_3310", geom="geom")
east <- st_read(con_alt, query="SELECT * FROM data.east_altadena_3310", geom="geom")

# residential parcel shapes
parcels <- st_read(con_alt, query="SELECT * FROM data.rel_assessor_altadena_parcels_jan2025", geom="geom")

# residential characteristics
res_data <- st_read(con_alt, query="SELECT * FROM data.rel_assessor_residential_jan2025")

# transform all shapes
west <- st_transform(west,4326) %>% ms_simplify()
east <- st_transform(east,4326) %>% ms_simplify()
eaton_fire <- st_transform(eaton_fire, 4326) %>% ms_simplify()
parcels <- st_transform(parcels,4326) 

# join parcel shapes to residential data
parcels <- parcels %>% left_join(res_data, by="ain")

# make one layer for mixed use and another layer for residential
parcels_res <- parcels %>% filter(residential==TRUE & total_units>0)

parcels_mixed <- parcels %>% filter(mixed_use==TRUE)


```

```{r, include=FALSE}
# residential type layer ----
# table(parcels_res$res_type) # filter out one boarding house
parcels_res <- parcels_res %>% filter(res_type!="Boarding house")

# create factor level
parcels_res$res_type_factor <- factor(
      parcels_res$res_type,
      levels = c("Multifamily","Condominium","Single-family") # Define the order of levels
    )

# Create a color palette based on the factor
res_pal <- colorFactor(palette = c("#F25922","#FF9E0D","#FFCC00"), domain = parcels_res$res_type_factor)

# total units layer ----
# table(parcels_res$total_units) # check numbers

# create typology
parcels_res <- parcels_res %>%
  mutate(unit_category=case_when(total_units==1 ~ "1",
                                 total_units>=2 & total_units<5 ~"2-4",
                                 total_units>=5 ~ "5 or more",
                                 TRUE ~ NA))

# table(parcels_res$unit_category) # check categories

# create factor level
parcels_res$unit_category_factor <- factor(
      parcels_res$unit_category,
      levels = c("1","2-4","5 or more") # Define the order of levels
    )

# Create a color palette based on the factor
unit_pal <- colorFactor(palette = c("#9BCCFF","#177FEB","#0860BC"), domain = parcels_res$unit_category_factor)


# homeowner layer ----
table(parcels_res$owner_renter, useNA='always') # check numbers

# recode further for simpler labels
parcels_res <- parcels_res %>%
  mutate(owner_renter_label=case_when(
    grepl("owner occupied|Owner occupied",owner_renter) ~ "Owner occupied/Likely owner occupied",
    owner_renter=="Sold to state" ~ "Sold to state/Government owned",
    owner_renter=="Government owned" ~ "Sold to state/Government owned",
     grepl("renter occupied|Renter occupied",owner_renter) ~ "Renter occupied/Owner & renter occupied",
    owner_renter=="Other ownership" ~ "Other",
    TRUE ~ owner_renter
  )) 

table(parcels_res$owner_renter_label, useNA='always') # check numbers

# create factor level
parcels_res$owner_renter_factor<- factor(
      parcels_res$owner_renter_label,
      levels = c("Owner occupied/Likely owner occupied","Renter occupied/Owner & renter occupied","Trust owned","Corporation owned","Sold to state/Government owned","Church or charity owned", "Other") # Define the order of levels
    )

# Create a color palette based on the factor
owner_pal <- colorFactor(palette = c( "#E9FFAA","#6EA400","#C27AA1","#733256","#6F6F6F","#BABABA", "#E0E0E0"), domain = parcels_res$owner_renter_factor)

# create popup
popup_res <-  paste0(
      "AIN: ", parcels_res$ain, "</br>",
      "Residential Type: ",  parcels_res$res_type, "</br>",
      "Ownership Type: ",  parcels_res$owner_renter, "</br>",
      "Units (Total/Rental): ",  parcels_res$total_units, "/", parcels_res$landlord_units, "</br>",
      "Total Square Feet: ", comma(parcels_res$total_square_feet), "</br>",
       "Use Code: ",  parcels_res$use_code)
```

```{r}
leaflet(
  width = "100%",
  height = "600px",
  options = leafletOptions(zoomSnap = 0.1, zoomDelta = 0.1,
                           attributionControl=FALSE)) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(-118.124, 34.1944, zoom = 13.5) %>%
  addPolygons(
    data=eaton_fire,
    fillColor="white",
    fillOpacity=0,
    color="black",
    weight=2.5,
    opacity=1,
    options=pathOptions(clickable=FALSE),
    group="Eaton Fire Perimeter") %>%
  addPolygons(
    data=east,
    fillColor="white",
    fillOpacity=0,
    color=meteorite,
    weight=2.5,
    opacity=1,
    popup=~"East Altadena",
    group="East Altadena") %>%
  addPolygons(
    data=west,
    fillColor="white",
    fillOpacity=0,
    color=ccblue,
    weight=2.5,
    opacity=1,
    popup=~"West Altadena",
    group="West Altadena") %>%
  addPolygons(
    data=parcels_res,
    fillColor=~res_pal(res_type_factor),
    fillOpacity=1,
    color="white",
    weight=.4,
    opacity=1,
    popup=~popup_res,
    group="Residential Property Types") %>%
  addLegend(
    position = "bottomright",
    pal = res_pal,
    values =  parcels_res$res_type_factor,
    group="Residential Property Types",
    title = "Residential Property Type",
    opacity=1) %>%
  addPolygons(
    data=parcels_res,
    fillColor=~unit_pal(unit_category_factor),
    fillOpacity=1,
    color="white",
    weight=.4,
    opacity=1,
    popup=~popup_res,
    group="Residential Unit Sizes") %>%
  addLegend(
    position = "bottomright",
    pal = unit_pal,
    values =  parcels_res$unit_category_factor,
    group="Residential Unit Sizes",
    title = "Number of Residential Units",
    opacity=1) %>%
  addPolygons(
    data=parcels_res,
    fillColor=~owner_pal(owner_renter_factor),
    fillOpacity=1,
    color="white",
    weight=.4,
    opacity=1,
    popup=~popup_res,
    group="Ownership Type") %>%
  addLegend(
    position = "bottomright",
    pal = owner_pal,
    values =  parcels_res$owner_renter_factor,
    group="Ownership Type",
    title = "Ownership Type",
    opacity = 1) %>%
  addPolygons(
    data=parcels_mixed,
    fillColor="#F25922",
    fillOpacity=1,
    color="white",
    weight=.2,
    opacity=1,
    popup=~res_type,
    group="Mixed Use Properties") %>%
  addLayersControl(
    overlayGroups = c("Residential Property Types","Residential Unit Sizes",
                      "Ownership Type","Mixed Use Properties","West Altadena",
                      "East Altadena","Eaton Fire Perimeter"),
    options = layersControlOptions(collapsed = FALSE))  %>%
  hideGroup(c("Eaton Fire Perimeter","Residential Unit Sizes","Ownership Type",
              "Mixed Use Properties")) %>% addFullscreenControl()

```

<style type="text/css">
.leaflet-right .leaflet-control {
  background-color: white;
  opacity: 1.0;
  padding: 2%;
  margin: 2px;
  width: 200px;
}
</style>