---
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"

---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE
)

# Library and environment set up ----

library(sf)
library(dplyr)
library(rmapshaper)
library(leaflet)
library(htmlwidgets)
options(scipen=999)

# Colors and Fonts ----
## COLORS ##
papaya <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

# Load in and prep shapes ----
source("W:\\RDA Team\\R\\credentials_source.R")

con_alt <- connect_to_db("altadena_recovery_rebuild")

# eaton fire shape -
eaton_fire <- st_read(con_alt, query="SELECT * FROM data.eaton_fire_prmtr_3310", geom="geom")

# east and west altadena boundaries --
west <- st_read(con_alt, query="SELECT * FROM data.west_altadena_3310", geom="geom") 
east <- st_read(con_alt, query="SELECT * FROM data.east_altadena_3310", geom="geom")

# residential parcel shapes
parcels <- st_read(con_alt, query="SELECT * FROM data.rel_assessor_altadena_parcels_jan2025", geom="geom")

# residential characteristics
res_data <- st_read(con_alt, query="SELECT * FROM data.rel_assessor_residential_jan2025")

# damage levels
damage <- st_read(con_alt, query="SELECT * FROM data.rel_assessor_damage_level")

# transform all shapes
west <- st_transform(west,4326) %>% ms_simplify()
east <- st_transform(east,4326) %>% ms_simplify()
eaton_fire <- st_transform(eaton_fire, 4326) %>% ms_simplify()
parcels <- st_transform(parcels,4326) 

# join parcel shapes to residential data
parcels <- parcels %>% left_join(res_data, by="ain") %>% left_join(damage, by="ain")

# make one layer for all residential - use this to visualize all properties
parcels_res <- parcels %>% filter(residential==TRUE & total_units>0) 

parcels_damaged <- parcels_res %>% filter(damage_category=="Significant Damage")


```

```{r, include=FALSE}
# all properties damage layer  ----
# table(parcels_res$res_type) # filter out one boarding house
parcels_res <- parcels_res %>% filter(res_type!="Boarding house")

# create factor level
parcels_res$damage_factor <- factor(
      parcels_res$damage_category,
      levels = c("No Damage","Some Damage","Significant Damage"))

# Create a color palette based on the factor
damage_pal <- colorFactor(palette = c("#FFCC00","#FF9E0D","#F25922"), domain = parcels_res$damage_factor)

popup_res <-  paste0(
      "AIN: ", parcels_res$ain, "</br>",
      "Damage Category: ",  parcels_res$damage_category, "</br>",
      "Residential Type: ",  parcels_res$res_type, "</br>",
      "Ownership Type: ",  parcels_res$owner_renter, "</br>",
      "Total/Rental Units: ",  parcels_res$total_units, "/", parcels_res$landlord_units, "</br>",
      "Total Square Feet: ", parcels_res$total_square_feet, "</br>",
      "Use Code: ",  parcels_res$use_code)


# make layer for rental units lost ------
rental_units <- parcels_res %>% filter(owner_renter=="Renter occupied") %>% filter(damage_category=="Significant Damage")
popup_rent <-  paste0(
      "AIN: ", rental_units$ain, "</br>",
      "Damage Category: ",  rental_units$damage_category, "</br>",
      "Residential Type: ",  rental_units$res_type, "</br>",
      "Ownership Type: ",  rental_units$owner_renter, "</br>",
      "Total/Rental Units: ",  rental_units$total_units, "/", rental_units$landlord_units, "</br>",
      "Total Square Feet: ", rental_units$total_square_feet, "</br>",
      "Use Code: ",  rental_units$use_code)

# make layer for single family units lost ------
single_family <- parcels_res %>% filter(res_type=="Single-family") %>% filter(damage_category=="Significant Damage")
popup_single <-  paste0(
      "AIN: ", single_family$ain, "</br>",
      "Damage Category: ",  single_family$damage_category, "</br>",
      "Residential Type: ",  single_family$res_type, "</br>",
      "Ownership Type: ",  single_family$owner_renter, "</br>",
      "Total/Rental Units: ",  single_family$total_units, "/", single_family$landlord_units, "</br>",
      "Total Square Feet: ", single_family$total_square_feet, "</br>",
      "Use Code: ",  single_family$use_code)

# make layer for multifamily units lost ------
multifamily <- parcels_res %>% filter(res_type=="Multifamily") %>% filter(damage_category=="Significant Damage")
popup_multi <-  paste0(
      "AIN: ", multifamily$ain, "</br>",
      "Damage Category: ",  multifamily$damage_category, "</br>",
      "Residential Type: ",  multifamily$res_type, "</br>",
      "Ownership Type: ",  multifamily$owner_renter, "</br>",
      "Total/Rental Units: ",  multifamily$total_units, "/", multifamily$landlord_units, "</br>",
      "Total Square Feet: ", multifamily$total_square_feet, "</br>",
      "Use Code: ",  multifamily$use_code)

```

```{r}
leaflet(
  width = "100%",
  height = "600px",
  options = leafletOptions(zoomSnap = 0.2, zoomDelta = 0.2,
                           attributionControl=FALSE)) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(-118.131, 34.1944, zoom = 13) %>%
  addPolygons(
    data=eaton_fire,
    fillColor="white",
    fillOpacity=0,
    color="black",
    weight=2.5,
    opacity=1,
    options=pathOptions(clickable=FALSE),
    group="Eaton Fire Perimeter") %>%
  addPolygons(
    data=east,
    fillColor="white",
    fillOpacity=0,
    color=meteorite,
    weight=2.5,
    opacity=1,
    popup=~"East Altadena",
    group="East Altadena") %>%
  addPolygons(
    data=west,
    fillColor="white",
    fillOpacity=0,
    color=ccblue,
    weight=2.5,
    opacity=1,
    popup=~"West Altadena",
    group="West Altadena") %>%
  addPolygons(
    data=parcels_res,
    fillColor=~damage_pal(damage_factor),
    fillOpacity=1,
    color="white",
    weight=.4,
    opacity=1,
    popup=~popup_res,
    group="Residential Properties Damage Levels") %>%
  addLegend(
    position = "bottomright",
    pal = damage_pal,
    values =  parcels_res$damage_factor,
    group="Residential Properties Damage Levels",
    title = "Damage Level",
    opacity=1) %>%
  addPolygons(
    data=rental_units,
    fillColor="black",
    color = "white",
    fillOpacity=1,
    weight=.3,
    opacity=1,
    popup=~popup_rent,
    group="Rental Properties Lost") %>%
  addPolygons(
    data=single_family,
    fillColor="black",
    color = "white",
    fillOpacity=1,
    weight=.3,
    opacity=1,
    popup=~popup_single,
    group="Single-family Properties Lost") %>%
  addPolygons(
    data=multifamily,
    fillColor="black",
    color = "white",
    fillOpacity=1,
    weight=.3,
    opacity=1,
    popup=~popup_multi,
    group="Multifamily Properties Lost") %>%
  addLayersControl(
    overlayGroups = c("Residential Properties Damage Levels",
                      "Rental Properties Lost", "Single-family Properties Lost",
                      "Multifamily Properties Lost", "West Altadena",
                      "East Altadena","Eaton Fire Perimeter"),
    options = layersControlOptions(collapsed = FALSE))  %>%
  hideGroup(c("Eaton Fire Perimeter", "Rental Properties Lost", 
              "Single-family Properties Lost", "Multifamily Properties Lost"))


```

<style type="text/css">
.leaflet-right .leaflet-control {
  background-color: white;
  opacity: 1.0;
  padding: 2%;
  margin: 2px;
  width: 200px;
}
</style>