---
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---

```{r, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE
)

## The following document outputs a visual for the altadena_housing_before_and_after.html 

#### Setting Up ####

library(usethis)
library(dplyr)
library(tidyverse)
library(htmltools) 
library(htmlwidgets)
library(gtExtras)
library(gt)
library(sf)
library(scales)
library(leaflet)
library(rmapshaper)

options(scipen=999)

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("altadena_recovery_rebuild")

## COLORS ##
orange <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"
```

```{r}
# Eaton Fire damaged properties
# residential parcel shapes
parcels <- st_read(con, query="SELECT * FROM data.rel_assessor_altadena_parcels_sept2025", geom="geom") %>% st_transform(4326)
res_data <- st_read(con, query="SELECT * FROM data.rel_assessor_residential_sept2025")
damage <- st_read(con, query="SELECT * FROM data.rel_assessor_damage_level_sept2025")
# join parcel shapes to residential data
parcels <- parcels %>% left_join(res_data, by="ain_sept") %>% left_join(damage, by="ain_sept")
# make one layer for all residential - use this to visualize all properties
parcels_res_damaged <- parcels %>% filter(residential==TRUE & total_units>0 & damage_category=="Significant Damage") 

# east and west altadena boundaries --
west <- st_read(con, query="SELECT * FROM data.west_altadena_3310", geom="geom") %>% st_transform(4326) %>% ms_simplify()
east <- st_read(con, query="SELECT * FROM data.east_altadena_3310", geom="geom") %>% st_transform(4326) %>%  ms_simplify()

df_lead <- st_read(con, query="Select * from data.lacdph_lead_results_grid_2025", geom="geom") %>% 
  st_transform(4326) %>%
  mutate(hi_lead_flag = case_when(is.na(lead_geometric_mean) ~ "Not Tested",
                               lead_geometric_mean >= 80 ~ "Above Threshold",
                               lead_geometric_mean <80 ~ "Below Threshold",
                               TRUE ~ NA))

#NOTE: taking time to transform even after filtering
df_zoning_lac <- st_read(con, query = "Select * FROM data.lac_unincorporated_zoning_3310 WHERE plng_area = 'West San Gabriel Valley'", geom="geom") %>% st_transform(4326)

df_local_fhsz <- st_read(con, query="Select * from data.eaton_local_fhsz_4326 WHERE fhsz_descr != 'NonWildland'", geom="geom")

df_state_fhsz <- st_read(con, query="Select * from data.eaton_state_fhsz_4326", geom="geom") 

eaton_fire <- st_read(con, query="SELECT * FROM data.eaton_fire_prmtr_3310", geom="geom") %>% st_transform(4326) %>%  ms_simplify()

#Pulling in data for POP UP 
sept_zoning <- st_read(con, query="SELECT * FROM data.rel_assessor_zoning_sept2025")
sept_fhsz <- st_read(con, query="SELECT * FROM data.rel_assessor_fhsz_sept2025") %>% select(-area_name)
sept_lead <- st_read(con, query="SELECT * FROM data.rel_assessor_lead_sept2025")
sept_sales <- dbGetQuery(con, statement = "SELECT ain_sept, sold_after_eaton, first_owner_name, first_owner_name_overflow, second_owner_name FROM data.rel_assessor_sales_sept2025;") %>%
  mutate(owner_names = str_squish(paste(first_owner_name, first_owner_name_overflow, second_owner_name))) %>%
  select(ain_sept, sold_after_eaton, owner_names)
sept_rebuild <- dbGetQuery(con, statement="SELECT ain as ain_jan, ain_sept, address_sept, rebuild_status
FROM data.rel_parcel_rebuild_status_2025_10
WHERE damage_category='Significant Damage';")
sept_contact <- dbGetQuery(con, "SELECT ain as ain_sept, mail_house_no, m_fraction, m_direction, m_street_name, m_unit, m_city_state, m_zip FROM data.assessor_data_universe_sept2025;") %>%
  # create clean address for contact
  mutate(
    street_part = trimws(paste(mail_house_no, m_fraction, m_direction, m_street_name)),
    # Add unit if present
    unit_part = ifelse(!is.na(m_unit) & trimws(m_unit) != "", paste0(", ", trimws(m_unit)), ""),
    city_zip_part = paste0(m_city_state, " ", substr(m_zip, 1, 5)),
    # Combine everything
    contact_address = str_squish(paste0(street_part, unit_part, ", ", city_zip_part))) %>%
  select(ain_sept, contact_address) %>% 
  filter(ain_sept %in% parcels_res_damaged$ain_sept)

all_df <- parcels_res_damaged %>% 
  left_join(sept_zoning, by = "ain_sept") %>% 
  left_join(sept_fhsz, by = "ain_sept") %>% 
  left_join(sept_lead, by="ain_sept") %>%
  left_join(sept_sales, by="ain_sept") %>%
  left_join(sept_contact, by = "ain_sept") %>%
  left_join(sept_rebuild, by="ain_sept")

### parcel pop up ----
popup_parcel <- paste0(
      "AIN: ", all_df$ain_sept, "</br>",
      "Parcel Address: ", all_df$address_sept, "</br>",
      "Residential Type: ",  all_df$res_type, "</br>",
      "Ownership Type: ",  all_df$owner_renter, "</br>",
      "Owner Name(s): ", all_df$owner_names, "</br>",
      "Owner Contact: ", all_df$contact_address, "</br>",
      "Total Square Footage: ", all_df$total_square_feet, "</br>",
      "Total Units: ", all_df$total_units, "</br>",
      "L.A. County Zoning: ",  all_df$z_desc, "</br>",
      "Fire Hazard Zone: ", all_df$combined_fhsz, "</br>",
      "Lead Level: ", all_df$hi_lead_label, "</br>",
      "Rebuild Status: ", all_df$rebuild_status, "</br>",
      "Sold After Eaton: ", all_df$sold_after_eaton
      )

### factors and paletes for other polygons ----
# high lead grid colors
df_lead$hi_lead_flag <- factor(
      df_lead$hi_lead_flag,
      levels = c("Not Tested","Below Threshold","Above Threshold"))

# Create a color palette based on the factor
lead_pal <- colorFactor(palette = c("gray","#ffcccc","red"), domain = df_lead$hi_lead_flag)

# fire zone colors
df_local_fhsz$fhsz_descr <- factor(
      df_local_fhsz$fhsz_descr,
      levels = c("Moderate","High","Very High"))

# Create a color palette based on the factor
colorpal_local_fhsz  <- colorFactor(palette = c("#ffffb2","#fd8d3c","#f03b20"), domain = df_local_fhsz$fhsz_descr)


# zone colors
# reference https://planning.lacounty.gov/wp-content/uploads/2022/04/map_z_02_Altadena.pdf
# table(df_zoning_lac$z_desc,useNA='always')
zoning_codes <- as.data.frame(table(df_zoning_lac$z_category,useNA='always'))
df_zoning_lac <- df_zoning_lac %>%
  mutate(zone_label=
           case_when(
             str_detect(z_category, "^C") ~ "Commercial",
             str_detect(z_category, "^A") ~ "Agricultural",
             str_detect(z_category, "^R-1") ~ "Single-Family Residence",
             str_detect(z_category, "^R-2") ~ "Two-Family Residence",
             str_detect(z_category, "^R-3") ~ "Multiple Residence",
             str_detect(z_category, "^R-4") ~ "Multiple Residence",
             str_detect(z_category, "^R-5") ~ "Multiple Residence",
             str_detect(z_category, "^R") ~ "Other Residential",
             str_detect(z_category, "^MXD") ~ "Mixed Use Development",
             str_detect(z_category, "^M-") ~ "Manufacturing",
             str_detect(z_category, "^O-") ~ "Open Space/Water Shed",
             str_detect(z_category, "^W-") ~ "Open Space/Water Shed",
             TRUE ~ "Other"))
# check
check <- df_zoning_lac %>% st_drop_geometry() %>% group_by(zone_label, z_category) %>% summarise(count=n())
             
df_zoning_lac$zone_label<- factor(
      df_zoning_lac$zone_label,
      levels = c("Single-Family Residence","Two-Family Residence","Multiple Residence","Other Residential","Mixed Use Development","Commercial","Manufacturing","Agricultural","Open Space/Water Shed","Other"))

# Create a color palette based on the factor
zoning_pal <- colorFactor(palette = c("#feffe2","#f2d84b","#d09a36","#dfd3b6","#b3605d","#E34234","#b7c4db","#c5fb5d","#8ffa4f","#bfbfbf"), domain = df_zoning_lac$zone_label)


```


```{r}
leaflet () %>%
addProviderTiles(providers$CartoDB.Positron) %>%
     setView(-118.131127, 34.194432, zoom = 13) %>%
  #Damaged/Destroyed Properties
  addPolygons(data=all_df,
                   fillColor="orange",
                   color = "orange",
                   fillOpacity=0.3,
                   weight=.6,
                   opacity=1,
                   popup = ~popup_parcel,
                   group="Significantly Damaged Parcels after Eaton Fire") %>%
  #Eaton Fire Perimeter
  addPolygons(data=eaton_fire,
              fillColor="white",
              fillOpacity=0,
              color="black",
              weight=2.5,
              opacity=1,
              options=pathOptions(clickable=FALSE),
              group="Eaton Fire Perimeter") %>%
  #East Perimeter
  addPolygons(data=east,
              fillColor="white",
              fillOpacity=0,
              color=meteorite,
              weight=2.5,
              opacity=1,
              options=pathOptions(clickable=FALSE),
              group="East Altadena") %>%
  #West Perimeter
  addPolygons(data=west,
              fillColor="white",
              fillOpacity=0,
              color=ccblue,
              weight=2.5,
              opacity=1,
              options=pathOptions(clickable=FALSE),
              group="West Altadena") %>%
  #Lead Data 
  addPolygons(data=df_lead,
              fillColor = ~lead_pal(hi_lead_flag),
              fillOpacity=0.4,
              color="white",
              weight=.5,
              opacity=1,
              popup=~paste0("Average Lead Level Measured in mg/kg: ", df_lead$lead_geometric_mean, "</br>",
                            "Higher than 80 mg/kg Safety Threshold: ", df_lead$hi_lead_flag),
              group="Lead Levels in Soil") %>% 
                addLegend(
                  position = "bottomleft",
                  pal = lead_pal,
                  values =  df_lead$hi_lead_flag,
                  group="Lead Levels in Soil",
                  title = "Lead Levels"
                ) %>%
  #Fire Hazard Zones 
  addPolygons(data=df_local_fhsz,
              fillColor=~colorpal_local_fhsz(fhsz_descr),
              fillOpacity=0.5,
              color="white",
              weight=1,
              popup=~fhsz_descr,
              group="Local Fire Hazard Zones") %>%
                addLegend(
                position = "bottomleft",
                pal = colorpal_local_fhsz,
                values =  df_local_fhsz$fhsz_descr,
                group="Local Fire Hazard Zones",
                title = "Fire Hazard Level") %>%
  addPolygons(data=df_state_fhsz,
              fillColor="red",
              fillOpacity=0.5,
              color="white",
              weight=1,
              popup=~fhsz_descr,
              group="State Fire Hazard Zones") %>%
  #Zoning 
  addPolygons(data=df_zoning_lac,
              fillColor=~zoning_pal(zone_label),
              fillOpacity=0.5,
              color="white",
              weight=1,
              opacity=1,
              popup=~paste0("Zoning Description: ", df_zoning_lac$z_desc),
              group="Zoning") %>%
                addLegend(
                position = "bottomleft",
                pal = zoning_pal,
                values =  df_zoning_lac$zone_label,
                group="Zoning",
                title = "Allowable Uses") %>% 
  #Controling Layers
  addLayersControl(
          overlayGroups = c("Significantly Damaged Parcels after Eaton Fire", "Lead Levels in Soil","Local Fire Hazard Zones","State Fire Hazard Zones","Zoning","West Altadena","East Altadena","Eaton Fire Perimeter"),
        options = layersControlOptions(collapsed = FALSE,autoZIndex = TRUE))  %>%
  hideGroup(c("Eaton Fire Perimeter","Lead Levels in Soil","Local Fire Hazard Zones","State Fire Hazard Zones","Zoning"))

```


```{r}
dbDisconnect(con)
```