---
title: ""
output: rmarkdown::html_vignette
# css: "W:\\RDA Team\\R\\cc_brandguide.css"

---

```{r, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE
)

## The following document outputs a visual of the housing stock before in a table format for the altadena_housing_before_and_after.html 

#### Setting Up ####

library(usethis)
library(dplyr)
library(tidyverse)
library(htmltools) 
library(htmlwidgets)
library(gtExtras)
library(gt)
library(sf)
library(scales)

options(scipen=999)

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("altadena_recovery_rebuild")

## COLORS ##
orange <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

```

In January 2025, West Altadena had a higher number of rental units than East Altadena at a count of 2,340. A greater share of rental units in West Altadena were in single-family homes compared to East Altadena (45% compared to 37%). Across Altadena, over half of rental units were in multifamily properties.  

```{r}
#### VISUAL ####
df_ <- st_read(con, query="Select res_type, area_name, rent_units_count, rent_units_prc from data.analysis_units_jan2025") 

df <- df_ %>%
  filter(res_type != "Boarding house") %>% 
  mutate("Count (%)"=paste0(comma(rent_units_count)," (",round(rent_units_prc,0),"%)"),
         "Share of Rental Units"=rent_units_prc,
         "Residential Type" = res_type,
         "Area" = str_to_title(area_name)) %>%
  mutate("Area" = factor(Area, levels = c("Altadena", "West", "East"))) %>%
  arrange(desc(rent_units_count)) 


table<- df %>%
  select("Area","Residential Type", "Share of Rental Units", "Count (%)")%>%
  gt(groupname_col = "Area", rowname_col = "Residential Type") %>%
  # tab_header(title= str_wrap("The majority of Alatadena comprises of single-family homes before the fire", width = 20))%>%
  tab_footnote(footnote=html("Catalyst California's calculations based on L.A. County Assessor Data, January 2025."),placement="left") 

 table%>%
  gt_plt_bar_pct(column= 'Share of Rental Units', scaled=FALSE, fill=meteorite, background="transparent")%>%
  # if needed modify column widths here 
  # cols_width(1~px(210),2~px(100),
  #            3~px(125))%>%
  opt_align_table_header("left")%>%
  opt_table_font(font=c("Inter", default_fonts())) %>% # opt_table_font(font=c(google_font(name="Inter"),locations=NULL,default_fonts()))%>%
  tab_options(table.background.color=alabaster,
    column_labels.background.color = "transparent",
    table.font.size = px(12),
    column_labels.font.size = px(12),
    heading.align = "left",
    table.font.names = "Inter",
    heading.title.font.size = px(20),
    heading.border.bottom.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = gainsboro,
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    data_row.padding = px(3),
    footnotes.font.size = px(10),
    footnotes.border.bottom.color = "transparent",
    table.align='left')%>%
  tab_style(style=
            cell_borders(sides=c("top","bottom"),color=gainsboro,style="solid",weight=px(1)),locations=cells_body())%>%
   tab_style(style=
            cell_text(font=c("Inter", default_fonts()),weight=900),locations=cells_title()) # cell_text(font=c(google_font(name="Inter"),default_fonts()),weight=900),locations=cells_title())


```


```{r, include=FALSE}
dbDisconnect(con) 
```