---
title: ""
output: rmarkdown::html_vignette
# css: "W:\\RDA Team\\R\\cc_brandguide.css"

---

```{r, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE
)

## The following document outputs a visual in a table format for the altadena_housing_before_and_after.html 

#### Setting Up ####

library(usethis)
library(dplyr)
library(tidyverse)
library(htmltools) 
library(htmlwidgets)
library(gtExtras)
library(gt)
library(sf)
library(scales)

options(scipen=999)

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("altadena_recovery_rebuild")

## COLORS ##
orange <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

```

```{r}
#### VISUAL ####
df_raw <- st_read(con, query="Select * from data.analysis_owner_renter_lead_damage") %>%
  #NOTE: line below is an attemp to reorder damage categories on the table but its NOT doing what I want it to.
  mutate(damage_category = factor(damage_category, c("Significant Damage", "Some Damage", "No Damage")))

df<- df_raw %>%
  mutate("Count (%)"=paste0(comma(count)," (",round(prc,0),"%)"),        
         "Damage in areas with lead levels higher than safety threshold"=prc,
         "Owner/Renter" = owner_renter,
         "Damage Level" = damage_category,
         "Area" = str_to_title(area)) %>%
  mutate("Area" = factor(Area, levels = c("Altadena", "West", "East"))) %>% 
  arrange(desc(count))


table<- df %>%
  select("Area","Owner/Renter", "Damage Level", "Damage in areas with lead levels higher than safety threshold", "Count (%)")%>%
  gt(groupname_col = c("Area", "Damage Level"), rowname_col = "Owner/Renter") %>%
  tab_footnote(footnote=html("Catalyst California's calculations based on L.A. County Assessor Data, January 2025 and CAL FIRE Damage Data, September 2025."),placement="left") 

 table%>%
  gt_plt_bar_pct(column= 'Damage in areas with lead levels higher than safety threshold', scaled=FALSE, fill=meteorite, background="transparent")%>%
  opt_align_table_header("left")%>%
  opt_table_font(font=c("Inter", default_fonts())) %>% 
  tab_options(table.background.color=alabaster,
    column_labels.background.color = "transparent",
    table.font.size = px(12),
    column_labels.font.size = px(12),
    heading.align = "left",
    table.font.names = "Inter",
    heading.title.font.size = px(20),
    heading.border.bottom.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = gainsboro,
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    data_row.padding = px(3),
    footnotes.font.size = px(10),
    footnotes.border.bottom.color = "transparent",
    table.align='left')%>%
  tab_style(style=
            cell_borders(sides=c("top","bottom"),color=gainsboro,style="solid",weight=px(1)),locations=cells_body())%>%
   tab_style(style=
            cell_text(font=c("Inter", default_fonts()),weight=900),locations=cells_title()) 

```

```{r, include=FALSE}
dbDisconnect(con) 
```