---
title: ""
output: html_document
css: "W:\\RDA Team\\R\\cc_brandguide.css"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE
)

## The following document outputs a visual of the housing stock before in a table format for the altadena_housing_before_and_after.html 

#### Setting Up ####

library(usethis)
library(dplyr)
library(tidyverse)
library(htmltools) 
library(htmlwidgets)
library(gtExtras)
library(gt)
library(sf)
library(scales)

options(scipen=999)

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("altadena_recovery_rebuild")

## COLORS ##
orange <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

```
West Altadena suffers the highest loss of rental units overall by count of homes that are significant damaged or destroyed. West Altadena renters also lost properties at rates higher than those in East Altadena.  

```{r}
#### VISUAL ####
df <- st_read(con, query="Select res_type, damage_category, area, rent_units, prc_rent from data.analysis_units_damage") %>%
  filter(res_type != "Boarding house",
         damage_category == "Significant Damage") %>% 
  mutate("Count (%)"=paste0(comma(rent_units)," (",round(prc_rent,0),"%)"),
         "Rental Units Lost"=prc_rent,
         "Residential Type" = res_type,
         "Area" = str_to_title(area)) %>%
  mutate("Area" = factor(Area, levels = c("Altadena", "West", "East"))) %>%
  arrange(desc(rent_units)) 


table<- df %>%
  select("Area","Residential Type", "Rental Units Lost", "Count (%)")%>%
  gt(groupname_col = "Area", rowname_col = "Residential Type") %>%
  # tab_header(title= str_wrap("The majority of Alatadena comprises of single-family homes before the fire", width = 20))%>%
  tab_footnote(footnote=html("Catalyst California's calculations based on LA County Assessor Data, Janaury 2025 and CAL FIRE Damage Data, September 2025."),placement="left") 

 table%>%
  gt_plt_bar_pct(column= 'Rental Units Lost', scaled=TRUE, fill=meteorite, background="transparent")%>%
  # if needed modify column widths here 
  cols_width(1~px(210),2~px(100),
             3~px(125))%>%
  opt_align_table_header("left")%>%
  opt_table_font(font=c(google_font(name="Inter"),locations=NULL,default_fonts()))%>%
  tab_options(table.background.color=alabaster,
    column_labels.background.color = "transparent",
    table.font.size = px(12),
    column_labels.font.size = px(12),
    heading.align = "left",
    table.font.names = "Inter",
    heading.title.font.size = px(20),
    heading.border.bottom.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = gainsboro,
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    data_row.padding = px(3),
    footnotes.font.size = px(10),
    footnotes.border.bottom.color = "transparent",
    table.align='left')%>%
  tab_style(style=
            cell_borders(sides=c("top","bottom"),color=gainsboro,style="solid",weight=px(1)),locations=cells_body())%>%
   tab_style(style=
            cell_text(font=c(google_font(name="Inter"),default_fonts()),weight=900),locations=cells_title())


```


```{r, include=FALSE}
dbDisconnect(con) 
```